### ISSUE TITLE
Readings in serie are not stable

### ISSUE THREAD

**Issue by marcellobarile** [marcellobarile/GrovePi#1]
The issue is not clear, in some circumstances the readings in serie returns strange values and a "cannot write to device" error is fired.

### Log

info GrovePi is initing
Air
-1
info onBusRes Error: Cannot write to device
info onBusRes     at i2c.writeBytes (/home/pi/micasa.pi/Node/node_modules/i2c/lib/i2c.coffee:91:19)
info onBusRes     at Object.module.exports.analogRead (/home/pi/micasa.pi/Node/libs/grovepi.js:203:9)
info onBusRes     at Object.module.exports.airQuality (/home/pi/micasa.pi/Node/libs/grovepi.js:374:10)
info onBusRes     at grovepi.run.grovepi.dht.dhtSensorErrorCounts (/home/pi/micasa.pi/Node/libs/sensors.js:44:17)
info onBusRes     at fn (/home/pi/micasa.pi/Node/node_modules/async/lib/async.js:641:34)
info onBusRes     at Object._onImmediate (/home/pi/micasa.pi/Node/node_modules/async/lib/async.js:557:34)
info onBusRes     at processImmediate [as _immediateCallback] (timers.js:330:15)
info onBusRes  [Error: Cannot write to device]
DHT
[ 19.9, 52.8, 77.19 ]
Light
434.78

Air
54
DHT
[ 6.189700196426902e+26,
  7.592662990849993e+36,
  -1.4240510622346686e+122 ]
info Error: Error reading length of bytes
info     at i2c.readBytes (/home/pi/micasa.pi/Node/node_modules/i2c/lib/i2c.coffee:109:19)
info     at Object.module.exports.read_i2c_block (/home/pi/micasa.pi/Node/libs/grovepi.js:142:16)
info     at Object.module.exports.dht (/home/pi/micasa.pi/Node/libs/grovepi.js:434:23)
info     at grovepi.run.grovepi.light.lightSensorErrorCounts (/home/pi/micasa.pi/Node/libs/sensors.js:58:17)
info     at fn (/home/pi/micasa.pi/Node/node_modules/async/lib/async.js:641:34)
info     at Object._onImmediate (/home/pi/micasa.pi/Node/node_modules/async/lib/async.js:557:34)
info     at processImmediate [as _immediateCallback] (timers.js:330:15)
info  [Error: Error reading length of bytes]
Light
0
info onBusRes Error: Cannot write to device
info onBusRes     at i2c.writeBytes (/home/pi/micasa.pi/Node/node_modules/i2c/lib/i2c.coffee:91:19)
info onBusRes     at Object.module.exports.analogRead (/home/pi/micasa.pi/Node/libs/grovepi.js:203:9)
info onBusRes     at Object.module.exports.light (/home/pi/micasa.pi/Node/libs/grovepi.js:396:10)
info onBusRes     at grovepi.run.socket.emit.roomTag (/home/pi/micasa.pi/Node/libs/sensors.js:72:17)
info onBusRes     at fn (/home/pi/micasa.pi/Node/node_modules/async/lib/async.js:641:34)
info onBusRes     at Object._onImmediate (/home/pi/micasa.pi/Node/node_modules/async/lib/async.js:557:34)
info onBusRes     at processImmediate [as _immediateCallback] (timers.js:330:15)
info onBusRes  [Error: Cannot write to device]

**Comment by marcellobarile** [comment]
It seems like the code which surrounds the grovepi calls (i.e. the "run()" call or the "init()" call) is interfering, in some way, with the module. I'm trying to isolate the block of code which is causing this strange behaviour.

**Comment by marcellobarile** [comment]
I did try to upgrade the RaspberryPi with the latest version of Raspbian and now it seems to work like a charm.

**Comment by marcellobarile** [comment]
I did try to upgrade the RaspberryPi with the latest version of Raspbian and now it seems to work like a charm.
